[TestFixture]
public class KnownUnannotatedAssembliesGenerationTests
{
    // Assemblies the generator probes. For each, it walks every member and looks
    // for ANY [StringSyntax(...)] — if zero are found, the assembly's simple name
    // is added to the deny-list. To extend coverage, drop a new entry here and
    // re-run; the test will rewrite the generated file and ask you to commit.
    static Assembly[] assemblies =
    [
        // System.Private.CoreLib
        typeof(string).Assembly,
        // System.Private.Uri
        typeof(Uri).Assembly,
        // System.Text.RegularExpressions
        typeof(Regex).Assembly,
        // System.Text.Json
        typeof(JsonDocument).Assembly,
        // System.Xml.ReaderWriter
        typeof(XmlDocument).Assembly,
        // System.Net.Http
        typeof(HttpClient).Assembly,
        // System.ComponentModel.Annotations
        typeof(System.ComponentModel.DataAnnotations.RegularExpressionAttribute).Assembly,
        // System.Data.Common
        typeof(System.Data.Common.DbCommand).Assembly,
        // Microsoft.EntityFrameworkCore
        typeof(Microsoft.EntityFrameworkCore.DbContext).Assembly,
        // Newtonsoft.Json
        typeof(Newtonsoft.Json.JsonConvert).Assembly,
        // Serilog
        typeof(Serilog.Log).Assembly
    ];

    const string targetFileName = "KnownUnannotatedAssemblies.Generated.cs";

    const string stringSyntaxAttributeFullName =
        "System.Diagnostics.CodeAnalysis.StringSyntaxAttribute";

    [Test]
    public void GeneratedFileIsUpToDate()
    {
        var unannotated = new SortedSet<string>(StringComparer.Ordinal);

        foreach (var assembly in assemblies.Distinct())
        {
            if (!HasAnyStringSyntax(assembly))
            {
                unannotated.Add(assembly.GetName().Name!);
            }
        }

        var generated = Render(unannotated);
        var path = LocateTargetFile();
        var existing = File.ReadAllText(path);

        if (existing == generated)
        {
            return;
        }

        File.WriteAllText(path, generated);
        Assert.Fail(
            $"{targetFileName} was out of date and has been rewritten. Re-run the test to confirm green, then commit.");
    }

    static bool HasAnyStringSyntax(Assembly assembly)
    {
        Type[] types;
        try
        {
            types = assembly.GetTypes();
        }
        catch (ReflectionTypeLoadException ex)
        {
            types = ex.Types.Where(_ => _ is not null).ToArray()!;
        }

        const BindingFlags flags =
            BindingFlags.Public |
            BindingFlags.NonPublic |
            BindingFlags.Static |
            BindingFlags.Instance |
            BindingFlags.DeclaredOnly;

        foreach (var type in types)
        {
            if (type is { IsPublic: false, IsNestedPublic: false })
            {
                continue;
            }

            foreach (var field in type.GetFields(flags))
            {
                if (HasStringSyntax(field.GetCustomAttributesData()))
                {
                    return true;
                }
            }

            foreach (var property in type.GetProperties(flags))
            {
                if (HasStringSyntax(property.GetCustomAttributesData()))
                {
                    return true;
                }
            }

            foreach (var method in type.GetMethods(flags))
            {
                if (MethodHasStringSyntax(method))
                {
                    return true;
                }
            }

            foreach (var ctor in type.GetConstructors(flags))
            {
                if (MethodHasStringSyntax(ctor))
                {
                    return true;
                }
            }
        }

        return false;
    }

    static bool MethodHasStringSyntax(MethodBase method)
    {
        foreach (var parameter in method.GetParameters())
        {
            if (HasStringSyntax(parameter.GetCustomAttributesData()))
            {
                return true;
            }
        }

        if (method is MethodInfo info &&
            HasStringSyntax(info.ReturnParameter.GetCustomAttributesData()))
        {
            return true;
        }

        return false;
    }

    static bool HasStringSyntax(IList<CustomAttributeData> attributes)
    {
        foreach (var attribute in attributes)
        {
            if (attribute.AttributeType.FullName == stringSyntaxAttributeFullName)
            {
                return true;
            }
        }

        return false;
    }

    static string Render(SortedSet<string> unannotated)
    {
        var builder = new StringBuilder();

        builder.Append(
            """
            // <auto-generated>
            //   Generated by KnownUnannotatedAssembliesGenerationTests. Do not edit by hand —
            //   re-run `dotnet test src/StringSyntaxAttributeAnalyzer.slnx --filter
            //   "FullyQualifiedName~KnownUnannotatedAssembliesGenerationTests"` to refresh.
            // </auto-generated>

            using System.Collections.Generic;

            public static partial class KnownUnannotatedAssemblies
            {
                public static readonly HashSet<string> Names = new(System.StringComparer.Ordinal)
                {

            """);

        foreach (var name in unannotated)
        {
            builder.Append(
                $"""
                         "{name}",

                 """);
        }

        builder.Append(
            """
                };
            }

            """);

        return builder.ToString().ReplaceLineEndings("\r\n");
    }

    static string LocateTargetFile()
    {
        var directory = new DirectoryInfo(TestContext.CurrentContext.TestDirectory);
        while (directory is not null)
        {
            var candidate = Path.Combine(
                directory.FullName,
                "StringSyntaxAttributeAnalyzer",
                targetFileName);
            if (File.Exists(candidate))
            {
                return candidate;
            }

            directory = directory.Parent;
        }

        throw new FileNotFoundException(
            $"Could not locate {targetFileName} walking up from {TestContext.CurrentContext.TestDirectory}");
    }
}
