// <auto-generated>
//   Generated by KnownUnannotatedAssembliesGenerationTests. Do not edit by hand —
//   re-run `dotnet test src/StringSyntaxAttributeAnalyzer.slnx --filter
//   "FullyQualifiedName~KnownUnannotatedAssembliesGenerationTests"` to refresh.
// </auto-generated>

using System.Collections.Generic;

public static partial class KnownUnannotatedAssemblies
{
    public static readonly HashSet<string> Names = new(System.StringComparer.Ordinal)
    {
        "Microsoft.EntityFrameworkCore",
        "Newtonsoft.Json",
        "Serilog",
        "System.Data.Common",
    };
}
