// Auto-curated deny-list: assemblies the generator scanned and confirmed contain
// zero [StringSyntax(...)] annotations. SSA002/SSA003/SSA005 are suppressed when
// the unfixable side (source for SSA002, target for SSA003, the bare side for
// SSA005) lives in one of these — there's no point asking a user to "add
// [StringSyntax]" to a third-party assembly they can't edit, and the absence
// of annotations on those assemblies isn't meaningful (the library author just
// hasn't adopted the attribute).
//
// The list is generated by KnownUnannotatedAssembliesGenerationTests so the
// curation stays in lock-step with the actual assembly state — if Newtonsoft
// or EF Core ever ships a [StringSyntax] anywhere, the next generator run will
// drop them off the deny-list automatically.
public static partial class KnownUnannotatedAssemblies
{
    public static bool Contains(ISymbol? symbol)
    {
        var name = symbol?.ContainingAssembly?.Name;
        return name is not null && Names.Contains(name);
    }
}
