[Generator]
public class SyntaxConstantsGenerator :
    IIncrementalGenerator
{
    const string globalsHeader =
        """
        // <auto-generated/>
        #nullable enable
        global using System.Diagnostics.CodeAnalysis;
        global using StringSyntaxAttributeAnalyzer;
        global using SyntaxAttribute = System.Diagnostics.CodeAnalysis.StringSyntaxAttribute;

        """;

    // Polyfill for System.Diagnostics.CodeAnalysis.StringSyntaxAttribute, which
    // only exists on net7+ / netstandard2.1 runtimes. Emitted as internal sealed
    // so consumers targeting netstandard2.0, net472, net6.0, etc. can still use
    // [StringSyntax(...)] — and so the Syntax constants below bind to something.
    // Skipped when the attribute is already visible from a referenced assembly.
    const string polyfillBody =
        """
        // <auto-generated/>
        #nullable enable
        namespace System.Diagnostics.CodeAnalysis;

        [System.AttributeUsage(System.AttributeTargets.Field | System.AttributeTargets.Parameter | System.AttributeTargets.Property, AllowMultiple = false)]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [System.Diagnostics.DebuggerNonUserCode]
        sealed class StringSyntaxAttribute : System.Attribute
        {
            public StringSyntaxAttribute(string syntax)
            {
                Syntax = syntax;
                Arguments = System.Array.Empty<object?>();
            }

            public StringSyntaxAttribute(string syntax, params object?[] arguments)
            {
                Syntax = syntax;
                Arguments = arguments;
            }

            public string Syntax { get; }
            public object?[] Arguments { get; }

            public const string CompositeFormat = nameof(CompositeFormat);
            public const string DateOnlyFormat = nameof(DateOnlyFormat);
            public const string DateTimeFormat = nameof(DateTimeFormat);
            public const string EnumFormat = nameof(EnumFormat);
            public const string GuidFormat = nameof(GuidFormat);
            public const string Json = nameof(Json);
            public const string NumericFormat = nameof(NumericFormat);
            public const string Regex = nameof(Regex);
            public const string TimeOnlyFormat = nameof(TimeOnlyFormat);
            public const string TimeSpanFormat = nameof(TimeSpanFormat);
            public const string Uri = nameof(Uri);
            public const string Xml = nameof(Xml);
        }
        """;

    const string typesBody =
        """
        // <auto-generated/>
        #nullable enable
        using System;
        using System.Diagnostics;
        using System.Diagnostics.CodeAnalysis;

        namespace StringSyntaxAttributeAnalyzer;

        /// <summary>
        /// Marks a field, parameter, or property as accepting any one of a set of
        /// string syntaxes. Compatible with <see cref="StringSyntaxAttribute"/> when
        /// the two sets overlap.
        /// </summary>
        [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        #pragma warning disable CS9113 // Parameter is unread — the analyzer reads it from metadata.
        sealed class UnionSyntaxAttribute(params string[] options) : System.Attribute;
        #pragma warning restore CS9113

        /// <summary>
        /// Declares the string syntax of a method's return value. Fills the gap left by
        /// <see cref="StringSyntaxAttribute"/>, whose AttributeUsage excludes methods and
        /// return values — so invocation results can participate in format analysis.
        /// TODO: remove when https://github.com/dotnet/runtime/issues/76203 ships and
        /// StringSyntaxAttribute targets Method/ReturnValue directly.
        /// </summary>
        [AttributeUsage(AttributeTargets.Method | AttributeTargets.Delegate, AllowMultiple = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        #pragma warning disable CS9113
        sealed class ReturnSyntaxAttribute(params string[] syntax) : System.Attribute;
        #pragma warning restore CS9113

        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        static class Syntax
        {
            /// <summary>The syntax identifier for strings containing composite formats for string formatting.</summary>
            public const string CompositeFormat = StringSyntaxAttribute.CompositeFormat;

            /// <summary>The syntax identifier for strings containing date format specifiers.</summary>
            public const string DateOnlyFormat = StringSyntaxAttribute.DateOnlyFormat;

            /// <summary>The syntax identifier for strings containing date and time format specifiers.</summary>
            public const string DateTimeFormat = StringSyntaxAttribute.DateTimeFormat;

            /// <summary>The syntax identifier for strings containing <see cref="System.Enum"/> format specifiers.</summary>
            public const string EnumFormat = StringSyntaxAttribute.EnumFormat;

            /// <summary>The syntax identifier for strings containing <see cref="System.Guid"/> format specifiers.</summary>
            public const string GuidFormat = StringSyntaxAttribute.GuidFormat;

            /// <summary>The syntax identifier for strings containing JavaScript Object Notation (JSON).</summary>
            public const string Json = StringSyntaxAttribute.Json;

            /// <summary>The syntax identifier for strings containing numeric format specifiers.</summary>
            public const string NumericFormat = StringSyntaxAttribute.NumericFormat;

            /// <summary>The syntax identifier for strings containing regular expressions.</summary>
            public const string Regex = StringSyntaxAttribute.Regex;

            /// <summary>The syntax identifier for strings containing time format specifiers.</summary>
            public const string TimeOnlyFormat = StringSyntaxAttribute.TimeOnlyFormat;

            /// <summary>The syntax identifier for strings containing <see cref="System.TimeSpan"/> format specifiers.</summary>
            public const string TimeSpanFormat = StringSyntaxAttribute.TimeSpanFormat;

            /// <summary>The syntax identifier for strings containing URIs.</summary>
            public const string Uri = nameof(Uri);

            /// <summary>The syntax identifier for strings containing XML.</summary>
            public const string Xml = nameof(Xml);

            /// <summary>The syntax identifier for strings containing HTML.</summary>
            public const string Html = nameof(Html);

            /// <summary>The syntax identifier for strings containing Text.</summary>
            public const string Text = nameof(Text);

            /// <summary>The syntax identifier for strings containing email addresses.</summary>
            public const string Email = nameof(Email);

            /// <summary>The syntax identifier for strings containing Markdown.</summary>
            public const string Markdown = nameof(Markdown);

            /// <summary>The syntax identifier for strings containing YAML.</summary>
            public const string Yaml = nameof(Yaml);

            /// <summary>The syntax identifier for strings containing CSV.</summary>
            public const string Csv = nameof(Csv);

            /// <summary>The syntax identifier for strings containing SQL.</summary>
            public const string Sql = nameof(Sql);
        }
        """;

    // The set of known constants for which shortcut attributes can be generated.
    // Kept in sync with the `Syntax` class above and with
    // `KnownShortcutAttributes` on the analyzer side.
    static readonly string[] shortcutNames =
    [
        "CompositeFormat",
        "DateOnlyFormat",
        "DateTimeFormat",
        "EnumFormat",
        "GuidFormat",
        "Json",
        "NumericFormat",
        "Regex",
        "TimeOnlyFormat",
        "TimeSpanFormat",
        "Uri",
        "Xml",
        "Html",
        "Text",
        "Email",
        "Markdown",
        "Yaml",
        "Csv",
        "Sql"
    ];

    static string BuildShortcutAttributesBody()
    {
        var builder = new StringBuilder();
        builder.Append(
            """
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Diagnostics;
            using System.Diagnostics.CodeAnalysis;

            namespace StringSyntaxAttributeAnalyzer;


            """);

        foreach (var name in shortcutNames)
        {
            builder.Append(
                $"""
                /// <summary>
                /// Shortcut for <c>[StringSyntax("{name}")]</c>. Only recognized by
                /// StringSyntaxAttributeAnalyzer — other analyzers (BCL, Roslyn) that look
                /// for <see cref="StringSyntaxAttribute"/> will not see this attribute.
                /// </summary>
                [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property | AttributeTargets.ReturnValue, AllowMultiple = false)]
                [ExcludeFromCodeCoverage]
                [DebuggerNonUserCode]
                sealed class {name}Attribute : System.Attribute;

                """);
        }

        return builder.ToString();
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The types (UnionSyntaxAttribute + Syntax class) ship into each consumer
        // assembly as internals. The global usings that make them friction-free to
        // use are opt-out via the `StringSyntaxAnalyzer_EmitGlobalUsings` MSBuild
        // property (surfaced through the props file packed under `build/`).
        // Shortcut-per-constant attributes (`[Html]`, `[Json]`, ...) are opt-IN via
        // `StringSyntaxAnalyzer_EmitShortcutAttributes=true` — they only carry
        // meaning inside projects that use this analyzer, so the default is off.
        //
        // If a referenced assembly already exposes the types to us (e.g. an
        // upstream project that grants InternalsVisibleTo), skip emitting them to
        // avoid CS0436 type-conflict warnings. The global usings still flow so
        // unqualified references bind to the upstream's copy.
        var typesAlreadyVisible = context.CompilationProvider.Select((compilation, _) =>
            IsTypeVisibleFromReference(compilation, "StringSyntaxAttributeAnalyzer.UnionSyntaxAttribute"));

        context.RegisterSourceOutput(typesAlreadyVisible, (ctx, alreadyVisible) =>
        {
            if (alreadyVisible)
            {
                return;
            }
            ctx.AddSource("Syntax.Types.g.cs", typesBody);
        });

        // Polyfill StringSyntaxAttribute when no referenced assembly exposes it
        // AND no in-compilation source defines it (e.g. via a source-only NuGet
        // package that drops the attribute into the consumer's own assembly).
        // Without the in-compilation check, both definitions would coexist and
        // every `StringSyntaxAttribute.X` member access in Syntax.Types.g.cs
        // would fail with CS0229 ambiguity.
        // The BCL ships it on net7+/netstandard2.1; older targets rely on this.
        var stringSyntaxAlreadyVisible = context.CompilationProvider.Select((compilation, _) =>
            IsTypeVisible(compilation, "System.Diagnostics.CodeAnalysis.StringSyntaxAttribute"));

        context.RegisterSourceOutput(stringSyntaxAlreadyVisible, (ctx, alreadyVisible) =>
        {
            if (alreadyVisible)
            {
                return;
            }
            ctx.AddSource("Syntax.Polyfill.g.cs", polyfillBody);
        });

        var emitGlobals = context.AnalyzerConfigOptionsProvider
            .Select((provider, _) =>
                !provider.GlobalOptions
                    .TryGetValue(
                        "build_property.StringSyntaxAnalyzer_EmitGlobalUsings",
                        out var value) ||
                !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(emitGlobals, (ctx, emit) =>
        {
            if (emit)
            {
                ctx.AddSource("Syntax.Globals.g.cs", globalsHeader);
            }
        });

        var shortcutsAlreadyVisible = context.CompilationProvider.Select((compilation, _) =>
            IsTypeVisibleFromReference(compilation, "StringSyntaxAttributeAnalyzer.HtmlAttribute"));

        var emitShortcuts = context.AnalyzerConfigOptionsProvider
            .Select((provider, _) =>
                provider.GlobalOptions
                    .TryGetValue(
                        "build_property.StringSyntaxAnalyzer_EmitShortcutAttributes",
                        out var value) &&
                string.Equals(value, "true", StringComparison.OrdinalIgnoreCase))
            .Combine(shortcutsAlreadyVisible);

        context.RegisterSourceOutput(emitShortcuts, (ctx, pair) =>
        {
            var (emit, alreadyVisible) = pair;
            if (emit && !alreadyVisible)
            {
                ctx.AddSource("Syntax.Shortcuts.g.cs", BuildShortcutAttributesBody());
            }
        });
    }

    static bool IsTypeVisibleFromReference(Compilation compilation, string metadataName)
    {
        var types = compilation.GetTypesByMetadataName(metadataName);
        var currentAssembly = compilation.Assembly;
        foreach (var type in types)
        {
            if (SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, currentAssembly))
            {
                continue;
            }
            if (compilation.IsSymbolAccessibleWithin(type, currentAssembly))
            {
                return true;
            }
        }
        return false;
    }

    // Like IsTypeVisibleFromReference but also returns true when the type is
    // defined in the current compilation (e.g. contributed by a source-only
    // NuGet package). Used for polyfill suppression to avoid emitting a second
    // copy that would collide with the source-only one.
    static bool IsTypeVisible(Compilation compilation, string metadataName)
    {
        var types = compilation.GetTypesByMetadataName(metadataName);
        var currentAssembly = compilation.Assembly;
        foreach (var type in types)
        {
            if (SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, currentAssembly))
            {
                return true;
            }
            if (compilation.IsSymbolAccessibleWithin(type, currentAssembly))
            {
                return true;
            }
        }
        return false;
    }
}
