namespace StringSyntaxAttributeAnalyzer;

[Generator]
public class SyntaxConstantsGenerator : IIncrementalGenerator
{
    const string Source = """
        // <auto-generated/>

        global using SyntaxAttribute = System.Diagnostics.CodeAnalysis.StringSyntaxAttribute;

        namespace StringSyntaxAttributeAnalyzer;

        using System.Diagnostics;
        using System.Diagnostics.CodeAnalysis;

        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        static class Syntax
        {
            /// <summary>The syntax identifier for strings containing composite formats for string formatting.</summary>
            public const string CompositeFormat = SyntaxAttribute.CompositeFormat;

            /// <summary>The syntax identifier for strings containing date format specifiers.</summary>
            public const string DateOnlyFormat = SyntaxAttribute.DateOnlyFormat;

            /// <summary>The syntax identifier for strings containing date and time format specifiers.</summary>
            public const string DateTimeFormat = SyntaxAttribute.DateTimeFormat;

            /// <summary>The syntax identifier for strings containing <see cref="System.Enum"/> format specifiers.</summary>
            public const string EnumFormat = SyntaxAttribute.EnumFormat;

            /// <summary>The syntax identifier for strings containing <see cref="System.Guid"/> format specifiers.</summary>
            public const string GuidFormat = SyntaxAttribute.GuidFormat;

            /// <summary>The syntax identifier for strings containing JavaScript Object Notation (JSON).</summary>
            public const string Json = SyntaxAttribute.Json;

            /// <summary>The syntax identifier for strings containing numeric format specifiers.</summary>
            public const string NumericFormat = SyntaxAttribute.NumericFormat;

            /// <summary>The syntax identifier for strings containing regular expressions.</summary>
            public const string Regex = SyntaxAttribute.Regex;

            /// <summary>The syntax identifier for strings containing time format specifiers.</summary>
            public const string TimeOnlyFormat = SyntaxAttribute.TimeOnlyFormat;

            /// <summary>The syntax identifier for strings containing <see cref="System.TimeSpan"/> format specifiers.</summary>
            public const string TimeSpanFormat = SyntaxAttribute.TimeSpanFormat;

            /// <summary>The syntax identifier for strings containing URIs.</summary>
            public const string Uri = nameof(Uri);

            /// <summary>The syntax identifier for strings containing XML.</summary>
            public const string Xml = nameof(Xml);

            /// <summary>The syntax identifier for strings containing HTML.</summary>
            public const string Html = nameof(Html);

            /// <summary>The syntax identifier for strings containing email addresses.</summary>
            public const string Email = nameof(Email);

            /// <summary>The syntax identifier for strings containing Markdown.</summary>
            public const string Markdown = nameof(Markdown);

            /// <summary>The syntax identifier for strings containing YAML.</summary>
            public const string Yaml = nameof(Yaml);

            /// <summary>The syntax identifier for strings containing CSV.</summary>
            public const string Csv = nameof(Csv);

            /// <summary>The syntax identifier for strings containing SQL.</summary>
            public const string Sql = nameof(Sql);
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(
            postInit => postInit.AddSource("Syntax.g.cs", Source));
}
