[Generator]
public class SyntaxConstantsGenerator :
    IIncrementalGenerator
{
    const string globalsHeader =
        """
        // <auto-generated/>
        global using System.Diagnostics.CodeAnalysis;
        global using StringSyntaxAttributeAnalyzer;
        global using SyntaxAttribute = System.Diagnostics.CodeAnalysis.StringSyntaxAttribute;

        """;

    const string typesBody =
        """
        // <auto-generated/>
        using System;
        using System.Diagnostics;
        using System.Diagnostics.CodeAnalysis;

        namespace StringSyntaxAttributeAnalyzer;

        /// <summary>
        /// Marks a field, parameter, or property as accepting any one of a set of
        /// string syntaxes. Compatible with <see cref="StringSyntaxAttribute"/> when
        /// the two sets overlap.
        /// </summary>
        [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        #pragma warning disable CS9113 // Parameter is unread — the analyzer reads it from metadata.
        sealed class UnionSyntaxAttribute(params string[] options) : System.Attribute;
        #pragma warning restore CS9113

        /// <summary>
        /// Declares the string syntax of a method's return value. Fills the gap left by
        /// <see cref="StringSyntaxAttribute"/>, whose AttributeUsage excludes methods and
        /// return values — so invocation results can participate in format analysis.
        /// TODO: remove when https://github.com/dotnet/runtime/issues/76203 ships and
        /// StringSyntaxAttribute targets Method/ReturnValue directly.
        /// </summary>
        [AttributeUsage(AttributeTargets.Method | AttributeTargets.Delegate, AllowMultiple = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        #pragma warning disable CS9113
        sealed class ReturnSyntaxAttribute(string syntax) : System.Attribute;
        #pragma warning restore CS9113

        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        static class Syntax
        {
            /// <summary>The syntax identifier for strings containing composite formats for string formatting.</summary>
            public const string CompositeFormat = SyntaxAttribute.CompositeFormat;

            /// <summary>The syntax identifier for strings containing date format specifiers.</summary>
            public const string DateOnlyFormat = SyntaxAttribute.DateOnlyFormat;

            /// <summary>The syntax identifier for strings containing date and time format specifiers.</summary>
            public const string DateTimeFormat = SyntaxAttribute.DateTimeFormat;

            /// <summary>The syntax identifier for strings containing <see cref="System.Enum"/> format specifiers.</summary>
            public const string EnumFormat = SyntaxAttribute.EnumFormat;

            /// <summary>The syntax identifier for strings containing <see cref="System.Guid"/> format specifiers.</summary>
            public const string GuidFormat = SyntaxAttribute.GuidFormat;

            /// <summary>The syntax identifier for strings containing JavaScript Object Notation (JSON).</summary>
            public const string Json = SyntaxAttribute.Json;

            /// <summary>The syntax identifier for strings containing numeric format specifiers.</summary>
            public const string NumericFormat = SyntaxAttribute.NumericFormat;

            /// <summary>The syntax identifier for strings containing regular expressions.</summary>
            public const string Regex = SyntaxAttribute.Regex;

            /// <summary>The syntax identifier for strings containing time format specifiers.</summary>
            public const string TimeOnlyFormat = SyntaxAttribute.TimeOnlyFormat;

            /// <summary>The syntax identifier for strings containing <see cref="System.TimeSpan"/> format specifiers.</summary>
            public const string TimeSpanFormat = SyntaxAttribute.TimeSpanFormat;

            /// <summary>The syntax identifier for strings containing URIs.</summary>
            public const string Uri = nameof(Uri);

            /// <summary>The syntax identifier for strings containing XML.</summary>
            public const string Xml = nameof(Xml);

            /// <summary>The syntax identifier for strings containing HTML.</summary>
            public const string Html = nameof(Html);

            /// <summary>The syntax identifier for strings containing Text.</summary>
            public const string Text = nameof(Text);

            /// <summary>The syntax identifier for strings containing email addresses.</summary>
            public const string Email = nameof(Email);

            /// <summary>The syntax identifier for strings containing Markdown.</summary>
            public const string Markdown = nameof(Markdown);

            /// <summary>The syntax identifier for strings containing YAML.</summary>
            public const string Yaml = nameof(Yaml);

            /// <summary>The syntax identifier for strings containing CSV.</summary>
            public const string Csv = nameof(Csv);

            /// <summary>The syntax identifier for strings containing SQL.</summary>
            public const string Sql = nameof(Sql);
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The types (UnionSyntaxAttribute + Syntax class) always ship. The global usings
        // that make them friction-free to use are opt-out via the
        // `StringSyntaxAnalyzer_EmitGlobalUsings` MSBuild property (surfaced through the
        // props file packed under `build/`).
        context.RegisterPostInitializationOutput(postInit => postInit.AddSource("Syntax.Types.g.cs", typesBody));

        var emitGlobals = context.AnalyzerConfigOptionsProvider
            .Select((provider, _) =>
                !provider.GlobalOptions
                    .TryGetValue(
                        "build_property.StringSyntaxAnalyzer_EmitGlobalUsings",
                        out var value) ||
                !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(emitGlobals, (ctx, emit) =>
        {
            if (emit)
            {
                ctx.AddSource("Syntax.Globals.g.cs", globalsHeader);
            }
        });
    }
}
